spring.application.name=gestion_inventario

spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_inventario
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/changelogMaster.yaml