spring.application.name=gestion_inventario

spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_inventario
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/changelogMaster.yaml

app.security.jwt.secret=${JWT_SECRET}
app.security.jwt.access-expiration=900000
app.security.jwt.refresh-expiration=604800000